CREATE DATABASE 4evar_test;

CREATE TABLE gen_info (
    variant_id VARCHAR(36) PRIMARY KEY,
    VAR_STRING VARCHAR(100) NOT NULL,
    CHROM CHAR(5) NOT NULL, 
    POS INT NOT NULL,
    REF VARCHAR(100) NOT NULL, 
    ALT VARCHAR(50) NOT NULL,
    VAF DECIMAL(7, 6), 
    GT VARCHAR(10),
    DP INT,
    GENE VARCHAR(100), 
    FEATURE_ID CHAR(20), 
    EFFECT VARCHAR(100), 
    HGVS_C VARCHAR(200), 
    HGVS_P VARCHAR(100), 
    ClinVar VARCHAR(500),
    ClinVarCONF VARCHAR(500),
    Varsome_link VARCHAR(500) NOT NULL, 
    Franklin_link VARCHAR(500) NOT NULL
);

