CREATE DATABASE 4evar_test;

CREATE TABLE gen_info (
    variant_id VARCHAR(36) PRIMARY KEY,
    CHROM CHAR(5) NOT NULL, 
    POS INT,
    REF CHAR(100), 
    ALT CHAR(50), 
    VAF DECIMAL(7, 6), 
    GT VARCHAR(10),
    DP INT,
    GENE CHAR(100), 
    FEATURE_ID CHAR(20), 
    EFFECT VARCHAR(100), 
    HGVS_C VARCHAR(200), 
    HGVS_P VARCHAR(100), 
    ClinVar VARCHAR(500),
    ClinVarCONF VARCHAR(500),
    Varsome_link VARCHAR(500) NOT NULL, 
    Franklin_link VARCHAR(500) NOT NULL
);

